apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage    ## 指定 StorageClass,PVC 中设置的该名称要和这里保持一致
  mountOptions:
    - hard
    - nfsvers=4.1                  ## 指定 NFS 版本
  nfs:
    server: 42.193.97.239           ## NFS 服务器的地址
    path: /nfs/prometheus          ## NFS 数据存储目录
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus
  labels:
    k8s-app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage   ## 指定 StorageClass
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      k8s-app: prometheus
