apiVersion: v1
kind: PersistentVolume
metadata:
  name: helm-jenkins-pv
  namespace: helm-jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/jenkins
    server: 42.193.97.239
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-jenkins
  namespace: helm-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
